# ==============================================================================
#  application-dev.properties – I.E. Micaela Bastidas Puyocahua
#  Configuración para Entorno de Desarrollo Local
# ==============================================================================

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logging
logging.level.com.colegio.bastidas=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
