# ==============================================================================
#  application-prod.properties – I.E. Micaela Bastidas Puyocahua
#  Configuración para Entorno de Producción
# ==============================================================================

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Logging
logging.level.root=WARN
logging.level.com.colegio.bastidas=INFO
logging.level.org.springframework.security=WARN

# Seguridad / HTTPS
server.forward-headers-strategy=native
